name: voting_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.14.0
  get_cli: ^1.8.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter_echarts: ^2.4.0
  cloud_firestore: ^4.8.2
  fl_chart: 0.62.0
  flutter: 
    sdk: flutter
  packages: 
    git: https://github.com/rahmat999ht/packages.git
  shared_preferences: ^2.2.0
  collection: ^1.17.0


dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

