// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVdq9KoB6TGtbk_TGdFskRX2-xs0oeEjM',
    appId: '1:782327443672:web:e823bcb4c42c6c964f27ad',
    messagingSenderId: '782327443672',
    projectId: 'voting-dcc3c',
    authDomain: 'voting-dcc3c.firebaseapp.com',
    storageBucket: 'voting-dcc3c.appspot.com',
    measurementId: 'G-TWKC4DE1JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6PvQi6MzxmeoNGtwn1sT_Bknho8Y100',
    appId: '1:782327443672:android:b6f639a4b1a6b2234f27ad',
    messagingSenderId: '782327443672',
    projectId: 'voting-dcc3c',
    storageBucket: 'voting-dcc3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--wijqHQMnewheWG6pg8ViizwSwJBvEU',
    appId: '1:782327443672:ios:48967695073742914f27ad',
    messagingSenderId: '782327443672',
    projectId: 'voting-dcc3c',
    storageBucket: 'voting-dcc3c.appspot.com',
    iosClientId: '782327443672-us4kd4e34qa5jkr3r290erj6c5c1t03i.apps.googleusercontent.com',
    iosBundleId: 'com.yayat.votingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--wijqHQMnewheWG6pg8ViizwSwJBvEU',
    appId: '1:782327443672:ios:48967695073742914f27ad',
    messagingSenderId: '782327443672',
    projectId: 'voting-dcc3c',
    storageBucket: 'voting-dcc3c.appspot.com',
    iosClientId: '782327443672-us4kd4e34qa5jkr3r290erj6c5c1t03i.apps.googleusercontent.com',
    iosBundleId: 'com.yayat.votingApp',
  );
}
